spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: learning_service
  datasource:
    url: jdbc:postgresql://${LEARNING_SERVICE_POSTGRES_HOST:localhost}:${LEARNING_SERVICE_POSTGRES_PORT:5432}/${LEARNING_SERVICE_POSTGRES_DB:learning_service_db}
    username: ${LEARNING_SERVICE_POSTGRES_USER:postgres}
    password: ${LEARNING_SERVICE_POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${LEARNING_SERVICE_SERVER_PORT:8082}
