from answer_service.domain.common.errors import AppError


class InfrastructureError(AppError): ...

class RepoError(InfrastructureError): ...

class EntityAddError(InfrastructureError): ...

class RollbackError(InfrastructureError): ...
