"""add_users_table

Revision ID: d15f6bc208de
Revises: 
Create Date: 2026-03-14 19:57:52.897193

"""
from collections.abc import Sequence

from sqlalchemy import Text

from answer_service.infrastructure.persistence.models.types import ChunkContentType, QuestionType, AnswerType

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d15f6bc208de"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("conversations",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("lesson_id", sa.UUID(), nullable=False),
    sa.Column("status", sa.String(length=50), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations"))
    )
    op.create_index(op.f("ix_conversations_lesson_id"), "conversations", ["lesson_id"], unique=False)
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_table("lesson_indexes",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("title", sa.String(length=512), nullable=False),
    sa.Column("status", sa.String(length=50), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_lesson_indexes"))
    )
    op.create_table("users",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_users"))
    )
    op.create_table("document_chunks",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("lesson_index_id", sa.UUID(), nullable=False),
    sa.Column("content", ChunkContentType(), nullable=False),
    sa.Column("position", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["lesson_index_id"], ["lesson_indexes.id"], name=op.f("fk_document_chunks_lesson_index_id_lesson_indexes"), ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks"))
    )
    op.create_index(op.f("ix_document_chunks_lesson_index_id"), "document_chunks", ["lesson_index_id"], unique=False)
    op.create_table("messages",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("conversation_id", sa.UUID(), nullable=False),
    sa.Column("question", QuestionType(), nullable=False),
    sa.Column("answer", AnswerType(astext_type=Text()), nullable=True),
    sa.Column("status", sa.String(length=50), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], name=op.f("fk_messages_conversation_id_conversations"), ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_messages"))
    )
    op.create_index(op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_document_chunks_lesson_index_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_table("users")
    op.drop_table("lesson_indexes")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_lesson_id"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
