export const mockCatalogData = [
  {
    id: 1,
    name: "Информационные технологии",
    icon: "💻",
    subcategories: [
      {
        id: 101,
        name: "Языки программирования",
        courses: [
          {
            id: 1001,
            title: "Python для начинающих",
            level: "beginner",
            duration: "40 часов",
            rating: 4.8,
            students: 15420,
          },
          {
            id: 1002,
            title: "SQL для анализа данных",
            level: "beginner",
            duration: "25 часов",
            rating: 4.7,
            students: 12340,
          },
          {
            id: 1003,
            title: "C/C++ с нуля",
            level: "beginner",
            duration: "50 часов",
            rating: 4.6,
            students: 9870,
          },
          {
            id: 1004,
            title: "Java для начинающих",
            level: "beginner",
            duration: "45 часов",
            rating: 4.7,
            students: 11230,
          },
          {
            id: 1005,
            title: "C# для разработчиков",
            level: "intermediate",
            duration: "35 часов",
            rating: 4.8,
            students: 8760,
          },
        ],
      },
      {
        id: 102,
        name: "Основы программирования",
        courses: [
          {
            id: 2001,
            title: "Алгоритмы и структуры данных",
            level: "beginner",
            duration: "30 часов",
            rating: 4.9,
            students: 21340,
          },
          {
            id: 2002,
            title: "Введение в разработку ПО",
            level: "beginner",
            duration: "20 часов",
            rating: 4.7,
            students: 18760,
          },
          {
            id: 2003,
            title: "Git для начинающих",
            level: "beginner",
            duration: "15 часов",
            rating: 4.9,
            students: 32450,
          },
          {
            id: 2004,
            title: "Базы данных для начинающих",
            level: "beginner",
            duration: "25 часов",
            rating: 4.6,
            students: 14320,
          },
          {
            id: 2005,
            title: "Тестирование ПО",
            level: "beginner",
            duration: "20 часов",
            rating: 4.5,
            students: 7650,
          },
        ],
      },
      {
        id: 103,
        name: "Веб-разработка",
        courses: [
          {
            id: 3001,
            title: "HTML/CSS для начинающих",
            level: "beginner",
            duration: "20 часов",
            rating: 4.8,
            students: 45670,
          },
          {
            id: 3002,
            title: "JavaScript с нуля",
            level: "beginner",
            duration: "35 часов",
            rating: 4.7,
            students: 23450,
          },
          {
            id: 3003,
            title: "React.js для начинающих",
            level: "intermediate",
            duration: "40 часов",
            rating: 4.9,
            students: 18760,
          },
          {
            id: 3004,
            title: "Node.js разработка",
            level: "intermediate",
            duration: "35 часов",
            rating: 4.7,
            students: 9870,
          },
          {
            id: 3005,
            title: "Vue.js с нуля",
            level: "intermediate",
            duration: "30 часов",
            rating: 4.6,
            students: 7650,
          },
        ],
      },
      {
        id: 104,
        name: "Мобильная разработка",
        courses: [
          {
            id: 4001,
            title: "Android разработка на Java",
            level: "intermediate",
            duration: "50 часов",
            rating: 4.7,
            students: 8760,
          },
          {
            id: 4002,
            title: "iOS разработка на Swift",
            level: "intermediate",
            duration: "55 часов",
            rating: 4.8,
            students: 6540,
          },
          {
            id: 4003,
            title: "Flutter с нуля",
            level: "beginner",
            duration: "40 часов",
            rating: 4.9,
            students: 12340,
          },
          {
            id: 4004,
            title: "React Native",
            level: "intermediate",
            duration: "35 часов",
            rating: 4.7,
            students: 5430,
          },
          {
            id: 4005,
            title: "Kotlin для Android",
            level: "intermediate",
            duration: "45 часов",
            rating: 4.8,
            students: 4320,
          },
        ],
      },
      {
        id: 105,
        name: "Data Science",
        courses: [
          {
            id: 5001,
            title: "Python для Data Science",
            level: "intermediate",
            duration: "45 часов",
            rating: 4.9,
            students: 15430,
          },
          {
            id: 5002,
            title: "Машинное обучение",
            level: "advanced",
            duration: "60 часов",
            rating: 4.9,
            students: 9870,
          },
          {
            id: 5003,
            title: "Анализ данных на Python",
            level: "intermediate",
            duration: "40 часов",
            rating: 4.8,
            students: 12340,
          },
          {
            id: 5004,
            title: "Нейронные сети",
            level: "advanced",
            duration: "55 часов",
            rating: 4.7,
            students: 6540,
          },
          {
            id: 5005,
            title: "SQL для аналитиков",
            level: "beginner",
            duration: "25 часов",
            rating: 4.6,
            students: 8760,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Дизайн",
    icon: "🎨",
    subcategories: [
      {
        id: 201,
        name: "Графический дизайн",
        courses: [
          {
            id: 6001,
            title: "Photoshop с нуля",
            level: "beginner",
            duration: "30 часов",
            rating: 4.7,
            students: 28760,
          },
          {
            id: 6002,
            title: "Illustrator для начинающих",
            level: "beginner",
            duration: "25 часов",
            rating: 4.6,
            students: 15430,
          },
          {
            id: 6003,
            title: "Adobe InDesign",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.5,
            students: 7650,
          },
          {
            id: 6004,
            title: "Типографика",
            level: "intermediate",
            duration: "15 часов",
            rating: 4.8,
            students: 5430,
          },
          {
            id: 6005,
            title: "Корпоративный стиль",
            level: "intermediate",
            duration: "25 часов",
            rating: 4.7,
            students: 4320,
          },
        ],
      },
      {
        id: 202,
        name: "UX/UI дизайн",
        courses: [
          {
            id: 7001,
            title: "Figma с нуля",
            level: "beginner",
            duration: "20 часов",
            rating: 4.9,
            students: 32450,
          },
          {
            id: 7002,
            title: "UX исследования",
            level: "intermediate",
            duration: "25 часов",
            rating: 4.7,
            students: 9870,
          },
          {
            id: 7003,
            title: "Прототипирование",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.8,
            students: 8760,
          },
          {
            id: 7004,
            title: "Дизайн систем",
            level: "advanced",
            duration: "30 часов",
            rating: 4.8,
            students: 5430,
          },
          {
            id: 7005,
            title: "Web дизайн",
            level: "intermediate",
            duration: "35 часов",
            rating: 4.9,
            students: 15430,
          },
        ],
      },
      {
        id: 203,
        name: "3D моделирование",
        courses: [
          {
            id: 8001,
            title: "Blender с нуля",
            level: "beginner",
            duration: "40 часов",
            rating: 4.8,
            students: 23450,
          },
          {
            id: 8002,
            title: "3ds Max для начинающих",
            level: "beginner",
            duration: "45 часов",
            rating: 4.6,
            students: 12340,
          },
          {
            id: 8003,
            title: "Maya основы",
            level: "intermediate",
            duration: "50 часов",
            rating: 4.7,
            students: 7650,
          },
          {
            id: 8004,
            title: "ZBrush скульптинг",
            level: "advanced",
            duration: "35 часов",
            rating: 4.8,
            students: 4320,
          },
          {
            id: 8005,
            title: "Cinema 4D",
            level: "intermediate",
            duration: "30 часов",
            rating: 4.7,
            students: 5430,
          },
        ],
      },
      {
        id: 204,
        name: "Веб-дизайн",
        courses: [
          {
            id: 9001,
            title: "Дизайн сайтов",
            level: "beginner",
            duration: "25 часов",
            rating: 4.7,
            students: 18760,
          },
          {
            id: 9002,
            title: "Адаптивный дизайн",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.8,
            students: 9870,
          },
          {
            id: 9003,
            title: "Tilda с нуля",
            level: "beginner",
            duration: "15 часов",
            rating: 4.9,
            students: 21340,
          },
          {
            id: 9004,
            title: "Webflow",
            level: "intermediate",
            duration: "25 часов",
            rating: 4.6,
            students: 6540,
          },
          {
            id: 9005,
            title: "Дизайн интернет-магазинов",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.7,
            students: 5430,
          },
        ],
      },
      {
        id: 205,
        name: "Motion design",
        courses: [
          {
            id: 10001,
            title: "After Effects с нуля",
            level: "beginner",
            duration: "35 часов",
            rating: 4.8,
            students: 15430,
          },
          {
            id: 10002,
            title: "2D анимация",
            level: "intermediate",
            duration: "30 часов",
            rating: 4.7,
            students: 8760,
          },
          {
            id: 10003,
            title: "3D анимация",
            level: "advanced",
            duration: "45 часов",
            rating: 4.6,
            students: 5430,
          },
          {
            id: 10004,
            title: "Моушн-графика",
            level: "intermediate",
            duration: "25 часов",
            rating: 4.8,
            students: 6540,
          },
          {
            id: 10005,
            title: "VFX для видео",
            level: "advanced",
            duration: "40 часов",
            rating: 4.7,
            students: 3210,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Маркетинг",
    icon: "📈",
    subcategories: [
      {
        id: 301,
        name: "SMM",
        courses: [
          {
            id: 11001,
            title: "SMM с нуля",
            level: "beginner",
            duration: "25 часов",
            rating: 4.7,
            students: 18760,
          },
          {
            id: 11002,
            title: "Instagram маркетинг",
            level: "beginner",
            duration: "20 часов",
            rating: 4.8,
            students: 21340,
          },
          {
            id: 11003,
            title: "Таргетинг ВКонтакте",
            level: "intermediate",
            duration: "15 часов",
            rating: 4.6,
            students: 12340,
          },
          {
            id: 11004,
            title: "Продвинутый SMM",
            level: "advanced",
            duration: "30 часов",
            rating: 4.8,
            students: 6540,
          },
          {
            id: 11005,
            title: "Telegram каналы",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.7,
            students: 8760,
          },
        ],
      },
      {
        id: 302,
        name: "SEO",
        courses: [
          {
            id: 12001,
            title: "SEO для начинающих",
            level: "beginner",
            duration: "20 часов",
            rating: 4.6,
            students: 14320,
          },
          {
            id: 12002,
            title: "Продвинутое SEO",
            level: "advanced",
            duration: "35 часов",
            rating: 4.7,
            students: 7650,
          },
          {
            id: 12003,
            title: "SEO оптимизация",
            level: "intermediate",
            duration: "25 часов",
            rating: 4.5,
            students: 5430,
          },
          {
            id: 12004,
            title: "Аудит сайтов",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.6,
            students: 4320,
          },
          {
            id: 12005,
            title: "SEO для e-commerce",
            level: "advanced",
            duration: "30 часов",
            rating: 4.7,
            students: 3210,
          },
        ],
      },
      {
        id: 303,
        name: "Контекстная реклама",
        courses: [
          {
            id: 13001,
            title: "Яндекс.Директ",
            level: "beginner",
            duration: "20 часов",
            rating: 4.7,
            students: 12340,
          },
          {
            id: 13002,
            title: "Google Ads",
            level: "beginner",
            duration: "25 часов",
            rating: 4.8,
            students: 9870,
          },
          {
            id: 13003,
            title: "Таргетинг в рекламе",
            level: "intermediate",
            duration: "15 часов",
            rating: 4.6,
            students: 6540,
          },
          {
            id: 13004,
            title: "Ретаргетинг",
            level: "intermediate",
            duration: "15 часов",
            rating: 4.7,
            students: 5430,
          },
          {
            id: 13005,
            title: "Аналитика рекламы",
            level: "advanced",
            duration: "25 часов",
            rating: 4.8,
            students: 4320,
          },
        ],
      },
      {
        id: 304,
        name: "Аналитика",
        courses: [
          {
            id: 14001,
            title: "Google Analytics",
            level: "beginner",
            duration: "20 часов",
            rating: 4.7,
            students: 14320,
          },
          {
            id: 14002,
            title: "Яндекс.Метрика",
            level: "beginner",
            duration: "15 часов",
            rating: 4.8,
            students: 12340,
          },
          {
            id: 14003,
            title: "Веб-аналитика",
            level: "intermediate",
            duration: "25 часов",
            rating: 4.6,
            students: 8760,
          },
          {
            id: 14004,
            title: "SQL для аналитиков",
            level: "intermediate",
            duration: "30 часов",
            rating: 4.8,
            students: 6540,
          },
          {
            id: 14005,
            title: "Data Studio",
            level: "intermediate",
            duration: "15 часов",
            rating: 4.7,
            students: 5430,
          },
        ],
      },
      {
        id: 305,
        name: "Email маркетинг",
        courses: [
          {
            id: 15001,
            title: "Email рассылки",
            level: "beginner",
            duration: "15 часов",
            rating: 4.6,
            students: 8760,
          },
          {
            id: 15002,
            title: "Автоворонки писем",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.7,
            students: 5430,
          },
          {
            id: 15003,
            title: "Создание писем",
            level: "beginner",
            duration: "10 часов",
            rating: 4.8,
            students: 6540,
          },
          {
            id: 15004,
            title: "Аналитика рассылок",
            level: "intermediate",
            duration: "15 часов",
            rating: 4.5,
            students: 3210,
          },
          {
            id: 15005,
            title: "Стратегия email",
            level: "advanced",
            duration: "20 часов",
            rating: 4.7,
            students: 2340,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Бизнес и управление",
    icon: "💼",
    subcategories: [
      {
        id: 401,
        name: "Управление проектами",
        courses: [
          {
            id: 16001,
            title: "Project Management",
            level: "beginner",
            duration: "25 часов",
            rating: 4.8,
            students: 15430,
          },
          {
            id: 16002,
            title: "Agile и Scrum",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.9,
            students: 21340,
          },
          {
            id: 16003,
            title: "Jira для команд",
            level: "beginner",
            duration: "15 часов",
            rating: 4.7,
            students: 9870,
          },
          {
            id: 16004,
            title: "Kanban методология",
            level: "intermediate",
            duration: "15 часов",
            rating: 4.6,
            students: 6540,
          },
          {
            id: 16005,
            title: "Управление рисками",
            level: "advanced",
            duration: "20 часов",
            rating: 4.7,
            students: 4320,
          },
        ],
      },
      {
        id: 402,
        name: "Стартапы",
        courses: [
          {
            id: 17001,
            title: "Как открыть стартап",
            level: "beginner",
            duration: "20 часов",
            rating: 4.8,
            students: 18760,
          },
          {
            id: 17002,
            title: "Бизнес-модели",
            level: "intermediate",
            duration: "15 часов",
            rating: 4.7,
            students: 12340,
          },
          {
            id: 17003,
            title: "Поиск инвестиций",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.6,
            students: 8760,
          },
          {
            id: 17004,
            title: "MVP разработка",
            level: "intermediate",
            duration: "25 часов",
            rating: 4.8,
            students: 6540,
          },
          {
            id: 17005,
            title: "Масштабирование",
            level: "advanced",
            duration: "30 часов",
            rating: 4.7,
            students: 4320,
          },
        ],
      },
      {
        id: 403,
        name: "Лидерство",
        courses: [
          {
            id: 18001,
            title: "Навыки лидера",
            level: "beginner",
            duration: "15 часов",
            rating: 4.7,
            students: 14320,
          },
          {
            id: 18002,
            title: "Управление командой",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.8,
            students: 9870,
          },
          {
            id: 18003,
            title: "Эмоциональный интеллект",
            level: "intermediate",
            duration: "15 часов",
            rating: 4.9,
            students: 7650,
          },
          {
            id: 18004,
            title: "Мотивация сотрудников",
            level: "intermediate",
            duration: "15 часов",
            rating: 4.7,
            students: 5430,
          },
          {
            id: 18005,
            title: "Корпоративная культура",
            level: "advanced",
            duration: "20 часов",
            rating: 4.6,
            students: 3210,
          },
        ],
      },
      {
        id: 404,
        name: "Финансы",
        courses: [
          {
            id: 19001,
            title: "Финансовая грамотность",
            level: "beginner",
            duration: "20 часов",
            rating: 4.8,
            students: 23450,
          },
          {
            id: 19002,
            title: "Управление бюджетом",
            level: "beginner",
            duration: "15 часов",
            rating: 4.7,
            students: 15430,
          },
          {
            id: 19003,
            title: "Инвестиции",
            level: "intermediate",
            duration: "25 часов",
            rating: 4.8,
            students: 12340,
          },
          {
            id: 19004,
            title: "Налоги для бизнеса",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.6,
            students: 8760,
          },
          {
            id: 19005,
            title: "Финансовый анализ",
            level: "advanced",
            duration: "30 часов",
            rating: 4.7,
            students: 5430,
          },
        ],
      },
      {
        id: 405,
        name: "Менеджмент",
        courses: [
          {
            id: 20001,
            title: "Основы менеджмента",
            level: "beginner",
            duration: "25 часов",
            rating: 4.7,
            students: 16540,
          },
          {
            id: 20002,
            title: "Стратегический менеджмент",
            level: "intermediate",
            duration: "30 часов",
            rating: 4.8,
            students: 9870,
          },
          {
            id: 20003,
            title: "Операционный менеджмент",
            level: "intermediate",
            duration: "25 часов",
            rating: 4.6,
            students: 7650,
          },
          {
            id: 20004,
            title: "Управление качеством",
            level: "advanced",
            duration: "20 часов",
            rating: 4.7,
            students: 5430,
          },
          {
            id: 20005,
            title: "Кросс-культурный менеджмент",
            level: "advanced",
            duration: "25 часов",
            rating: 4.5,
            students: 3210,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Иностранные языки",
    icon: "🌍",
    subcategories: [
      {
        id: 501,
        name: "Английский язык",
        courses: [
          {
            id: 21001,
            title: "Английский для начинающих",
            level: "beginner",
            duration: "40 часов",
            rating: 4.9,
            students: 45670,
          },
          {
            id: 21002,
            title: "Разговорный английский",
            level: "intermediate",
            duration: "35 часов",
            rating: 4.8,
            students: 32450,
          },
          {
            id: 21003,
            title: "Бизнес английский",
            level: "intermediate",
            duration: "30 часов",
            rating: 4.8,
            students: 21340,
          },
          {
            id: 21004,
            title: "Английский для IT",
            level: "intermediate",
            duration: "25 часов",
            rating: 4.9,
            students: 18760,
          },
          {
            id: 21005,
            title: "Подготовка к IELTS",
            level: "advanced",
            duration: "45 часов",
            rating: 4.7,
            students: 15430,
          },
        ],
      },
      {
        id: 502,
        name: "Немецкий язык",
        courses: [
          {
            id: 22001,
            title: "Немецкий с нуля",
            level: "beginner",
            duration: "40 часов",
            rating: 4.7,
            students: 14320,
          },
          {
            id: 22002,
            title: "Разговорный немецкий",
            level: "intermediate",
            duration: "35 часов",
            rating: 4.6,
            students: 8760,
          },
          {
            id: 22003,
            title: "Немецкий для работы",
            level: "intermediate",
            duration: "30 часов",
            rating: 4.7,
            students: 6540,
          },
          {
            id: 22004,
            title: "Экзамен Goethe",
            level: "advanced",
            duration: "40 часов",
            rating: 4.6,
            students: 4320,
          },
          {
            id: 22005,
            title: "Немецкий для путешествий",
            level: "beginner",
            duration: "20 часов",
            rating: 4.8,
            students: 9870,
          },
        ],
      },
      {
        id: 503,
        name: "Французский язык",
        courses: [
          {
            id: 23001,
            title: "Французский для начинающих",
            level: "beginner",
            duration: "40 часов",
            rating: 4.7,
            students: 12340,
          },
          {
            id: 23002,
            title: "Разговорный французский",
            level: "intermediate",
            duration: "35 часов",
            rating: 4.6,
            students: 7650,
          },
          {
            id: 23003,
            title: "Французский для бизнеса",
            level: "intermediate",
            duration: "30 часов",
            rating: 4.5,
            students: 5430,
          },
          {
            id: 23004,
            title: "Подготовка к DELF",
            level: "advanced",
            duration: "45 часов",
            rating: 4.7,
            students: 3210,
          },
          {
            id: 23005,
            title: "Французская культура",
            level: "intermediate",
            duration: "20 часов",
            rating: 4.8,
            students: 4320,
          },
        ],
      },
      {
        id: 504,
        name: "Испанский язык",
        courses: [
          {
            id: 24001,
            title: "Испанский с нуля",
            level: "beginner",
            duration: "40 часов",
            rating: 4.8,
            students: 15430,
          },
          {
            id: 24002,
            title: "Разговорный испанский",
            level: "intermediate",
            duration: "35 часов",
            rating: 4.7,
            students: 9870,
          },
          {
            id: 24003,
            title: "Испанский для путешествий",
            level: "beginner",
            duration: "20 часов",
            rating: 4.9,
            students: 12340,
          },
          {
            id: 24004,
            title: "DELE подготовка",
            level: "advanced",
            duration: "45 часов",
            rating: 4.6,
            students: 5430,
          },
          {
            id: 24005,
            title: "Латиноамериканский испанский",
            level: "intermediate",
            duration: "30 часов",
            rating: 4.7,
            students: 4320,
          },
        ],
      },
      {
        id: 505,
        name: "Китайский язык",
        courses: [
          {
            id: 25001,
            title: "Китайский для начинающих",
            level: "beginner",
            duration: "50 часов",
            rating: 4.7,
            students: 18760,
          },
          {
            id: 25002,
            title: "Иероглифика",
            level: "beginner",
            duration: "30 часов",
            rating: 4.6,
            students: 12340,
          },
          {
            id: 25003,
            title: "Разговорный китайский",
            level: "intermediate",
            duration: "40 часов",
            rating: 4.7,
            students: 8760,
          },
          {
            id: 25004,
            title: "Бизнес китайский",
            level: "intermediate",
            duration: "35 часов",
            rating: 4.5,
            students: 5430,
          },
          {
            id: 25005,
            title: "Подготовка к HSK",
            level: "advanced",
            duration: "55 часов",
            rating: 4.8,
            students: 4320,
          },
        ],
      },
    ],
  },
];
