export const mockCourses = [
  {
    "id": 1001,
    "title": "Python для начинающих",
    "authorId": "author-101",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 101,
    "subcategoryName": "Языки программирования",
    "level": "beginner",
    "durationLabel": "40 часов",
    "rating": 4.8,
    "studentsCount": 15420,
    "lessonsCount": 23,
    "testsCount": 6,
    "tasksCount": 9,
    "shortDescription": "Стартовый курс по теме «Python для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 1002,
    "title": "SQL для анализа данных",
    "authorId": "author-101",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 101,
    "subcategoryName": "Языки программирования",
    "level": "beginner",
    "durationLabel": "25 часов",
    "rating": 4.7,
    "studentsCount": 12340,
    "lessonsCount": 16,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «SQL для анализа данных» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 1003,
    "title": "C/C++ с нуля",
    "authorId": "author-101",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 101,
    "subcategoryName": "Языки программирования",
    "level": "beginner",
    "durationLabel": "50 часов",
    "rating": 4.6,
    "studentsCount": 9870,
    "lessonsCount": 31,
    "testsCount": 7,
    "tasksCount": 9,
    "shortDescription": "Стартовый курс по теме «C/C++ с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 1004,
    "title": "Java для начинающих",
    "authorId": "author-101",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 101,
    "subcategoryName": "Языки программирования",
    "level": "beginner",
    "durationLabel": "45 часов",
    "rating": 4.7,
    "studentsCount": 11230,
    "lessonsCount": 25,
    "testsCount": 6,
    "tasksCount": 10,
    "shortDescription": "Стартовый курс по теме «Java для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 1005,
    "title": "C# для разработчиков",
    "authorId": "author-101",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 101,
    "subcategoryName": "Языки программирования",
    "level": "intermediate",
    "durationLabel": "35 часов",
    "rating": 4.8,
    "studentsCount": 8760,
    "lessonsCount": 24,
    "testsCount": 6,
    "tasksCount": 7,
    "shortDescription": "Практический курс по теме «C# для разработчиков» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 2001,
    "title": "Алгоритмы и структуры данных",
    "authorId": "author-102",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 102,
    "subcategoryName": "Основы программирования",
    "level": "beginner",
    "durationLabel": "30 часов",
    "rating": 4.9,
    "studentsCount": 21340,
    "lessonsCount": 18,
    "testsCount": 5,
    "tasksCount": 5,
    "shortDescription": "Стартовый курс по теме «Алгоритмы и структуры данных» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 2002,
    "title": "Введение в разработку ПО",
    "authorId": "author-102",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 102,
    "subcategoryName": "Основы программирования",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.7,
    "studentsCount": 18760,
    "lessonsCount": 13,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «Введение в разработку ПО» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 2003,
    "title": "Git для начинающих",
    "authorId": "author-102",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 102,
    "subcategoryName": "Основы программирования",
    "level": "beginner",
    "durationLabel": "15 часов",
    "rating": 4.9,
    "studentsCount": 32450,
    "lessonsCount": 11,
    "testsCount": 3,
    "tasksCount": 5,
    "shortDescription": "Стартовый курс по теме «Git для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 2004,
    "title": "Базы данных для начинающих",
    "authorId": "author-102",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 102,
    "subcategoryName": "Основы программирования",
    "level": "beginner",
    "durationLabel": "25 часов",
    "rating": 4.6,
    "studentsCount": 14320,
    "lessonsCount": 14,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «Базы данных для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 2005,
    "title": "Тестирование ПО",
    "authorId": "author-102",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 102,
    "subcategoryName": "Основы программирования",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.5,
    "studentsCount": 7650,
    "lessonsCount": 12,
    "testsCount": 4,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «Тестирование ПО» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 3001,
    "title": "HTML/CSS для начинающих",
    "authorId": "author-103",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 103,
    "subcategoryName": "Веб-разработка",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.8,
    "studentsCount": 45670,
    "lessonsCount": 12,
    "testsCount": 4,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «HTML/CSS для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 3002,
    "title": "JavaScript с нуля",
    "authorId": "author-103",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 103,
    "subcategoryName": "Веб-разработка",
    "level": "beginner",
    "durationLabel": "35 часов",
    "rating": 4.7,
    "studentsCount": 23450,
    "lessonsCount": 21,
    "testsCount": 4,
    "tasksCount": 8,
    "shortDescription": "Стартовый курс по теме «JavaScript с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 3003,
    "title": "React.js для начинающих",
    "authorId": "author-103",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 103,
    "subcategoryName": "Веб-разработка",
    "level": "intermediate",
    "durationLabel": "40 часов",
    "rating": 4.9,
    "studentsCount": 18760,
    "lessonsCount": 29,
    "testsCount": 7,
    "tasksCount": 8,
    "shortDescription": "Практический курс по теме «React.js для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 3004,
    "title": "Node.js разработка",
    "authorId": "author-103",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 103,
    "subcategoryName": "Веб-разработка",
    "level": "intermediate",
    "durationLabel": "35 часов",
    "rating": 4.7,
    "studentsCount": 9870,
    "lessonsCount": 23,
    "testsCount": 5,
    "tasksCount": 8,
    "shortDescription": "Практический курс по теме «Node.js разработка» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 3005,
    "title": "Vue.js с нуля",
    "authorId": "author-103",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 103,
    "subcategoryName": "Веб-разработка",
    "level": "intermediate",
    "durationLabel": "30 часов",
    "rating": 4.6,
    "studentsCount": 7650,
    "lessonsCount": 21,
    "testsCount": 5,
    "tasksCount": 8,
    "shortDescription": "Практический курс по теме «Vue.js с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 4001,
    "title": "Android разработка на Java",
    "authorId": "author-104",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 104,
    "subcategoryName": "Мобильная разработка",
    "level": "intermediate",
    "durationLabel": "50 часов",
    "rating": 4.7,
    "studentsCount": 8760,
    "lessonsCount": 34,
    "testsCount": 8,
    "tasksCount": 12,
    "shortDescription": "Практический курс по теме «Android разработка на Java» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 4002,
    "title": "iOS разработка на Swift",
    "authorId": "author-104",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 104,
    "subcategoryName": "Мобильная разработка",
    "level": "intermediate",
    "durationLabel": "55 часов",
    "rating": 4.8,
    "studentsCount": 6540,
    "lessonsCount": 38,
    "testsCount": 8,
    "tasksCount": 11,
    "shortDescription": "Практический курс по теме «iOS разработка на Swift» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 4003,
    "title": "Flutter с нуля",
    "authorId": "author-104",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 104,
    "subcategoryName": "Мобильная разработка",
    "level": "beginner",
    "durationLabel": "40 часов",
    "rating": 4.9,
    "studentsCount": 12340,
    "lessonsCount": 25,
    "testsCount": 6,
    "tasksCount": 8,
    "shortDescription": "Стартовый курс по теме «Flutter с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 4004,
    "title": "React Native",
    "authorId": "author-104",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 104,
    "subcategoryName": "Мобильная разработка",
    "level": "intermediate",
    "durationLabel": "35 часов",
    "rating": 4.7,
    "studentsCount": 5430,
    "lessonsCount": 23,
    "testsCount": 5,
    "tasksCount": 9,
    "shortDescription": "Практический курс по теме «React Native» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 4005,
    "title": "Kotlin для Android",
    "authorId": "author-104",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 104,
    "subcategoryName": "Мобильная разработка",
    "level": "intermediate",
    "durationLabel": "45 часов",
    "rating": 4.8,
    "studentsCount": 4320,
    "lessonsCount": 30,
    "testsCount": 7,
    "tasksCount": 9,
    "shortDescription": "Практический курс по теме «Kotlin для Android» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 5001,
    "title": "Python для Data Science",
    "authorId": "author-105",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 105,
    "subcategoryName": "Data Science",
    "level": "intermediate",
    "durationLabel": "45 часов",
    "rating": 4.9,
    "studentsCount": 15430,
    "lessonsCount": 30,
    "testsCount": 7,
    "tasksCount": 9,
    "shortDescription": "Практический курс по теме «Python для Data Science» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 5002,
    "title": "Машинное обучение",
    "authorId": "author-105",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 105,
    "subcategoryName": "Data Science",
    "level": "advanced",
    "durationLabel": "60 часов",
    "rating": 4.9,
    "studentsCount": 9870,
    "lessonsCount": 47,
    "testsCount": 10,
    "tasksCount": 16,
    "shortDescription": "Продвинутый курс по теме «Машинное обучение» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 5003,
    "title": "Анализ данных на Python",
    "authorId": "author-105",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 105,
    "subcategoryName": "Data Science",
    "level": "intermediate",
    "durationLabel": "40 часов",
    "rating": 4.8,
    "studentsCount": 12340,
    "lessonsCount": 29,
    "testsCount": 7,
    "tasksCount": 10,
    "shortDescription": "Практический курс по теме «Анализ данных на Python» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 5004,
    "title": "Нейронные сети",
    "authorId": "author-105",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 105,
    "subcategoryName": "Data Science",
    "level": "advanced",
    "durationLabel": "55 часов",
    "rating": 4.7,
    "studentsCount": 6540,
    "lessonsCount": 41,
    "testsCount": 9,
    "tasksCount": 14,
    "shortDescription": "Продвинутый курс по теме «Нейронные сети» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 5005,
    "title": "SQL для аналитиков",
    "authorId": "author-105",
    "categoryId": 1,
    "categoryName": "Информационные технологии",
    "categoryIcon": "💻",
    "subcategoryId": 105,
    "subcategoryName": "Data Science",
    "level": "beginner",
    "durationLabel": "25 часов",
    "rating": 4.6,
    "studentsCount": 8760,
    "lessonsCount": 15,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Стартовый курс по теме «SQL для аналитиков» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 6001,
    "title": "Photoshop с нуля",
    "authorId": "author-201",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 201,
    "subcategoryName": "Графический дизайн",
    "level": "beginner",
    "durationLabel": "30 часов",
    "rating": 4.7,
    "studentsCount": 28760,
    "lessonsCount": 18,
    "testsCount": 5,
    "tasksCount": 6,
    "shortDescription": "Стартовый курс по теме «Photoshop с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 6002,
    "title": "Illustrator для начинающих",
    "authorId": "author-201",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 201,
    "subcategoryName": "Графический дизайн",
    "level": "beginner",
    "durationLabel": "25 часов",
    "rating": 4.6,
    "studentsCount": 15430,
    "lessonsCount": 16,
    "testsCount": 3,
    "tasksCount": 6,
    "shortDescription": "Стартовый курс по теме «Illustrator для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 6003,
    "title": "Adobe InDesign",
    "authorId": "author-201",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 201,
    "subcategoryName": "Графический дизайн",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.5,
    "studentsCount": 7650,
    "lessonsCount": 16,
    "testsCount": 4,
    "tasksCount": 4,
    "shortDescription": "Практический курс по теме «Adobe InDesign» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 6004,
    "title": "Типографика",
    "authorId": "author-201",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 201,
    "subcategoryName": "Графический дизайн",
    "level": "intermediate",
    "durationLabel": "15 часов",
    "rating": 4.8,
    "studentsCount": 5430,
    "lessonsCount": 10,
    "testsCount": 2,
    "tasksCount": 4,
    "shortDescription": "Практический курс по теме «Типографика» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 6005,
    "title": "Корпоративный стиль",
    "authorId": "author-201",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 201,
    "subcategoryName": "Графический дизайн",
    "level": "intermediate",
    "durationLabel": "25 часов",
    "rating": 4.7,
    "studentsCount": 4320,
    "lessonsCount": 17,
    "testsCount": 5,
    "tasksCount": 7,
    "shortDescription": "Практический курс по теме «Корпоративный стиль» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 7001,
    "title": "Figma с нуля",
    "authorId": "author-202",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 202,
    "subcategoryName": "UX/UI дизайн",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.9,
    "studentsCount": 32450,
    "lessonsCount": 12,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Стартовый курс по теме «Figma с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 7002,
    "title": "UX исследования",
    "authorId": "author-202",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 202,
    "subcategoryName": "UX/UI дизайн",
    "level": "intermediate",
    "durationLabel": "25 часов",
    "rating": 4.7,
    "studentsCount": 9870,
    "lessonsCount": 18,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Практический курс по теме «UX исследования» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 7003,
    "title": "Прототипирование",
    "authorId": "author-202",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 202,
    "subcategoryName": "UX/UI дизайн",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.8,
    "studentsCount": 8760,
    "lessonsCount": 16,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Практический курс по теме «Прототипирование» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 7004,
    "title": "Дизайн систем",
    "authorId": "author-202",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 202,
    "subcategoryName": "UX/UI дизайн",
    "level": "advanced",
    "durationLabel": "30 часов",
    "rating": 4.8,
    "studentsCount": 5430,
    "lessonsCount": 23,
    "testsCount": 5,
    "tasksCount": 10,
    "shortDescription": "Продвинутый курс по теме «Дизайн систем» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 7005,
    "title": "Web дизайн",
    "authorId": "author-202",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 202,
    "subcategoryName": "UX/UI дизайн",
    "level": "intermediate",
    "durationLabel": "35 часов",
    "rating": 4.9,
    "studentsCount": 15430,
    "lessonsCount": 24,
    "testsCount": 6,
    "tasksCount": 7,
    "shortDescription": "Практический курс по теме «Web дизайн» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 8001,
    "title": "Blender с нуля",
    "authorId": "author-203",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 203,
    "subcategoryName": "3D моделирование",
    "level": "beginner",
    "durationLabel": "40 часов",
    "rating": 4.8,
    "studentsCount": 23450,
    "lessonsCount": 23,
    "testsCount": 6,
    "tasksCount": 7,
    "shortDescription": "Стартовый курс по теме «Blender с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 8002,
    "title": "3ds Max для начинающих",
    "authorId": "author-203",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 203,
    "subcategoryName": "3D моделирование",
    "level": "beginner",
    "durationLabel": "45 часов",
    "rating": 4.6,
    "studentsCount": 12340,
    "lessonsCount": 27,
    "testsCount": 6,
    "tasksCount": 9,
    "shortDescription": "Стартовый курс по теме «3ds Max для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 8003,
    "title": "Maya основы",
    "authorId": "author-203",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 203,
    "subcategoryName": "3D моделирование",
    "level": "intermediate",
    "durationLabel": "50 часов",
    "rating": 4.7,
    "studentsCount": 7650,
    "lessonsCount": 36,
    "testsCount": 8,
    "tasksCount": 12,
    "shortDescription": "Практический курс по теме «Maya основы» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 8004,
    "title": "ZBrush скульптинг",
    "authorId": "author-203",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 203,
    "subcategoryName": "3D моделирование",
    "level": "advanced",
    "durationLabel": "35 часов",
    "rating": 4.8,
    "studentsCount": 4320,
    "lessonsCount": 26,
    "testsCount": 6,
    "tasksCount": 9,
    "shortDescription": "Продвинутый курс по теме «ZBrush скульптинг» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 8005,
    "title": "Cinema 4D",
    "authorId": "author-203",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 203,
    "subcategoryName": "3D моделирование",
    "level": "intermediate",
    "durationLabel": "30 часов",
    "rating": 4.7,
    "studentsCount": 5430,
    "lessonsCount": 21,
    "testsCount": 5,
    "tasksCount": 7,
    "shortDescription": "Практический курс по теме «Cinema 4D» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 9001,
    "title": "Дизайн сайтов",
    "authorId": "author-204",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 204,
    "subcategoryName": "Веб-дизайн",
    "level": "beginner",
    "durationLabel": "25 часов",
    "rating": 4.7,
    "studentsCount": 18760,
    "lessonsCount": 15,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Стартовый курс по теме «Дизайн сайтов» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 9002,
    "title": "Адаптивный дизайн",
    "authorId": "author-204",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 204,
    "subcategoryName": "Веб-дизайн",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.8,
    "studentsCount": 9870,
    "lessonsCount": 15,
    "testsCount": 3,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «Адаптивный дизайн» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 9003,
    "title": "Tilda с нуля",
    "authorId": "author-204",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 204,
    "subcategoryName": "Веб-дизайн",
    "level": "beginner",
    "durationLabel": "15 часов",
    "rating": 4.9,
    "studentsCount": 21340,
    "lessonsCount": 11,
    "testsCount": 3,
    "tasksCount": 3,
    "shortDescription": "Стартовый курс по теме «Tilda с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 9004,
    "title": "Webflow",
    "authorId": "author-204",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 204,
    "subcategoryName": "Веб-дизайн",
    "level": "intermediate",
    "durationLabel": "25 часов",
    "rating": 4.6,
    "studentsCount": 6540,
    "lessonsCount": 16,
    "testsCount": 4,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «Webflow» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 9005,
    "title": "Дизайн интернет-магазинов",
    "authorId": "author-204",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 204,
    "subcategoryName": "Веб-дизайн",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.7,
    "studentsCount": 5430,
    "lessonsCount": 14,
    "testsCount": 4,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «Дизайн интернет-магазинов» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 10001,
    "title": "After Effects с нуля",
    "authorId": "author-205",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 205,
    "subcategoryName": "Motion design",
    "level": "beginner",
    "durationLabel": "35 часов",
    "rating": 4.8,
    "studentsCount": 15430,
    "lessonsCount": 20,
    "testsCount": 5,
    "tasksCount": 8,
    "shortDescription": "Стартовый курс по теме «After Effects с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 10002,
    "title": "2D анимация",
    "authorId": "author-205",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 205,
    "subcategoryName": "Motion design",
    "level": "intermediate",
    "durationLabel": "30 часов",
    "rating": 4.7,
    "studentsCount": 8760,
    "lessonsCount": 22,
    "testsCount": 4,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «2D анимация» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 10003,
    "title": "3D анимация",
    "authorId": "author-205",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 205,
    "subcategoryName": "Motion design",
    "level": "advanced",
    "durationLabel": "45 часов",
    "rating": 4.6,
    "studentsCount": 5430,
    "lessonsCount": 37,
    "testsCount": 9,
    "tasksCount": 12,
    "shortDescription": "Продвинутый курс по теме «3D анимация» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 10004,
    "title": "Моушн-графика",
    "authorId": "author-205",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 205,
    "subcategoryName": "Motion design",
    "level": "intermediate",
    "durationLabel": "25 часов",
    "rating": 4.8,
    "studentsCount": 6540,
    "lessonsCount": 16,
    "testsCount": 4,
    "tasksCount": 7,
    "shortDescription": "Практический курс по теме «Моушн-графика» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 10005,
    "title": "VFX для видео",
    "authorId": "author-205",
    "categoryId": 2,
    "categoryName": "Дизайн",
    "categoryIcon": "🎨",
    "subcategoryId": 205,
    "subcategoryName": "Motion design",
    "level": "advanced",
    "durationLabel": "40 часов",
    "rating": 4.7,
    "studentsCount": 3210,
    "lessonsCount": 31,
    "testsCount": 8,
    "tasksCount": 10,
    "shortDescription": "Продвинутый курс по теме «VFX для видео» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 11001,
    "title": "SMM с нуля",
    "authorId": "author-301",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 301,
    "subcategoryName": "SMM",
    "level": "beginner",
    "durationLabel": "25 часов",
    "rating": 4.7,
    "studentsCount": 18760,
    "lessonsCount": 15,
    "testsCount": 4,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «SMM с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 11002,
    "title": "Instagram маркетинг",
    "authorId": "author-301",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 301,
    "subcategoryName": "SMM",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.8,
    "studentsCount": 21340,
    "lessonsCount": 13,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «Instagram маркетинг» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 11003,
    "title": "Таргетинг ВКонтакте",
    "authorId": "author-301",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 301,
    "subcategoryName": "SMM",
    "level": "intermediate",
    "durationLabel": "15 часов",
    "rating": 4.6,
    "studentsCount": 12340,
    "lessonsCount": 13,
    "testsCount": 3,
    "tasksCount": 5,
    "shortDescription": "Практический курс по теме «Таргетинг ВКонтакте» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 11004,
    "title": "Продвинутый SMM",
    "authorId": "author-301",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 301,
    "subcategoryName": "SMM",
    "level": "advanced",
    "durationLabel": "30 часов",
    "rating": 4.8,
    "studentsCount": 6540,
    "lessonsCount": 23,
    "testsCount": 5,
    "tasksCount": 8,
    "shortDescription": "Продвинутый курс по теме «Продвинутый SMM» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 11005,
    "title": "Telegram каналы",
    "authorId": "author-301",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 301,
    "subcategoryName": "SMM",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.7,
    "studentsCount": 8760,
    "lessonsCount": 14,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Практический курс по теме «Telegram каналы» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 12001,
    "title": "SEO для начинающих",
    "authorId": "author-302",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 302,
    "subcategoryName": "SEO",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.6,
    "studentsCount": 14320,
    "lessonsCount": 12,
    "testsCount": 4,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «SEO для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 12002,
    "title": "Продвинутое SEO",
    "authorId": "author-302",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 302,
    "subcategoryName": "SEO",
    "level": "advanced",
    "durationLabel": "35 часов",
    "rating": 4.7,
    "studentsCount": 7650,
    "lessonsCount": 28,
    "testsCount": 6,
    "tasksCount": 11,
    "shortDescription": "Продвинутый курс по теме «Продвинутое SEO» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 12003,
    "title": "SEO оптимизация",
    "authorId": "author-302",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 302,
    "subcategoryName": "SEO",
    "level": "intermediate",
    "durationLabel": "25 часов",
    "rating": 4.5,
    "studentsCount": 5430,
    "lessonsCount": 19,
    "testsCount": 5,
    "tasksCount": 5,
    "shortDescription": "Практический курс по теме «SEO оптимизация» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 12004,
    "title": "Аудит сайтов",
    "authorId": "author-302",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 302,
    "subcategoryName": "SEO",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.6,
    "studentsCount": 4320,
    "lessonsCount": 13,
    "testsCount": 3,
    "tasksCount": 5,
    "shortDescription": "Практический курс по теме «Аудит сайтов» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 12005,
    "title": "SEO для e-commerce",
    "authorId": "author-302",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 302,
    "subcategoryName": "SEO",
    "level": "advanced",
    "durationLabel": "30 часов",
    "rating": 4.7,
    "studentsCount": 3210,
    "lessonsCount": 24,
    "testsCount": 6,
    "tasksCount": 10,
    "shortDescription": "Продвинутый курс по теме «SEO для e-commerce» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 13001,
    "title": "Яндекс.Директ",
    "authorId": "author-303",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 303,
    "subcategoryName": "Контекстная реклама",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.7,
    "studentsCount": 12340,
    "lessonsCount": 12,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Стартовый курс по теме «Яндекс.Директ» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 13002,
    "title": "Google Ads",
    "authorId": "author-303",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 303,
    "subcategoryName": "Контекстная реклама",
    "level": "beginner",
    "durationLabel": "25 часов",
    "rating": 4.8,
    "studentsCount": 9870,
    "lessonsCount": 16,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «Google Ads» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 13003,
    "title": "Таргетинг в рекламе",
    "authorId": "author-303",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 303,
    "subcategoryName": "Контекстная реклама",
    "level": "intermediate",
    "durationLabel": "15 часов",
    "rating": 4.6,
    "studentsCount": 6540,
    "lessonsCount": 13,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Практический курс по теме «Таргетинг в рекламе» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 13004,
    "title": "Ретаргетинг",
    "authorId": "author-303",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 303,
    "subcategoryName": "Контекстная реклама",
    "level": "intermediate",
    "durationLabel": "15 часов",
    "rating": 4.7,
    "studentsCount": 5430,
    "lessonsCount": 10,
    "testsCount": 2,
    "tasksCount": 5,
    "shortDescription": "Практический курс по теме «Ретаргетинг» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 13005,
    "title": "Аналитика рекламы",
    "authorId": "author-303",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 303,
    "subcategoryName": "Контекстная реклама",
    "level": "advanced",
    "durationLabel": "25 часов",
    "rating": 4.8,
    "studentsCount": 4320,
    "lessonsCount": 20,
    "testsCount": 5,
    "tasksCount": 6,
    "shortDescription": "Продвинутый курс по теме «Аналитика рекламы» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 14001,
    "title": "Google Analytics",
    "authorId": "author-304",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 304,
    "subcategoryName": "Аналитика",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.7,
    "studentsCount": 14320,
    "lessonsCount": 12,
    "testsCount": 4,
    "tasksCount": 3,
    "shortDescription": "Стартовый курс по теме «Google Analytics» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 14002,
    "title": "Яндекс.Метрика",
    "authorId": "author-304",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 304,
    "subcategoryName": "Аналитика",
    "level": "beginner",
    "durationLabel": "15 часов",
    "rating": 4.8,
    "studentsCount": 12340,
    "lessonsCount": 10,
    "testsCount": 2,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «Яндекс.Метрика» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 14003,
    "title": "Веб-аналитика",
    "authorId": "author-304",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 304,
    "subcategoryName": "Аналитика",
    "level": "intermediate",
    "durationLabel": "25 часов",
    "rating": 4.6,
    "studentsCount": 8760,
    "lessonsCount": 19,
    "testsCount": 5,
    "tasksCount": 7,
    "shortDescription": "Практический курс по теме «Веб-аналитика» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 14004,
    "title": "SQL для аналитиков",
    "authorId": "author-304",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 304,
    "subcategoryName": "Аналитика",
    "level": "intermediate",
    "durationLabel": "30 часов",
    "rating": 4.8,
    "studentsCount": 6540,
    "lessonsCount": 20,
    "testsCount": 4,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «SQL для аналитиков» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 14005,
    "title": "Data Studio",
    "authorId": "author-304",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 304,
    "subcategoryName": "Аналитика",
    "level": "intermediate",
    "durationLabel": "15 часов",
    "rating": 4.7,
    "studentsCount": 5430,
    "lessonsCount": 11,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Практический курс по теме «Data Studio» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 15001,
    "title": "Email рассылки",
    "authorId": "author-305",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 305,
    "subcategoryName": "Email маркетинг",
    "level": "beginner",
    "durationLabel": "15 часов",
    "rating": 4.6,
    "studentsCount": 8760,
    "lessonsCount": 10,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «Email рассылки» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 15002,
    "title": "Автоворонки писем",
    "authorId": "author-305",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 305,
    "subcategoryName": "Email маркетинг",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.7,
    "studentsCount": 5430,
    "lessonsCount": 15,
    "testsCount": 3,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «Автоворонки писем» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 15003,
    "title": "Создание писем",
    "authorId": "author-305",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 305,
    "subcategoryName": "Email маркетинг",
    "level": "beginner",
    "durationLabel": "10 часов",
    "rating": 4.8,
    "studentsCount": 6540,
    "lessonsCount": 10,
    "testsCount": 2,
    "tasksCount": 3,
    "shortDescription": "Стартовый курс по теме «Создание писем» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 15004,
    "title": "Аналитика рассылок",
    "authorId": "author-305",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 305,
    "subcategoryName": "Email маркетинг",
    "level": "intermediate",
    "durationLabel": "15 часов",
    "rating": 4.5,
    "studentsCount": 3210,
    "lessonsCount": 10,
    "testsCount": 2,
    "tasksCount": 4,
    "shortDescription": "Практический курс по теме «Аналитика рассылок» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 15005,
    "title": "Стратегия email",
    "authorId": "author-305",
    "categoryId": 3,
    "categoryName": "Маркетинг",
    "categoryIcon": "📈",
    "subcategoryId": 305,
    "subcategoryName": "Email маркетинг",
    "level": "advanced",
    "durationLabel": "20 часов",
    "rating": 4.7,
    "studentsCount": 2340,
    "lessonsCount": 16,
    "testsCount": 4,
    "tasksCount": 7,
    "shortDescription": "Продвинутый курс по теме «Стратегия email» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 16001,
    "title": "Project Management",
    "authorId": "author-401",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 401,
    "subcategoryName": "Управление проектами",
    "level": "beginner",
    "durationLabel": "25 часов",
    "rating": 4.8,
    "studentsCount": 15430,
    "lessonsCount": 15,
    "testsCount": 4,
    "tasksCount": 6,
    "shortDescription": "Стартовый курс по теме «Project Management» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 16002,
    "title": "Agile и Scrum",
    "authorId": "author-401",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 401,
    "subcategoryName": "Управление проектами",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.9,
    "studentsCount": 21340,
    "lessonsCount": 15,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Практический курс по теме «Agile и Scrum» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 16003,
    "title": "Jira для команд",
    "authorId": "author-401",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 401,
    "subcategoryName": "Управление проектами",
    "level": "beginner",
    "durationLabel": "15 часов",
    "rating": 4.7,
    "studentsCount": 9870,
    "lessonsCount": 11,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «Jira для команд» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 16004,
    "title": "Kanban методология",
    "authorId": "author-401",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 401,
    "subcategoryName": "Управление проектами",
    "level": "intermediate",
    "durationLabel": "15 часов",
    "rating": 4.6,
    "studentsCount": 6540,
    "lessonsCount": 10,
    "testsCount": 2,
    "tasksCount": 5,
    "shortDescription": "Практический курс по теме «Kanban методология» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 16005,
    "title": "Управление рисками",
    "authorId": "author-401",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 401,
    "subcategoryName": "Управление проектами",
    "level": "advanced",
    "durationLabel": "20 часов",
    "rating": 4.7,
    "studentsCount": 4320,
    "lessonsCount": 16,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Продвинутый курс по теме «Управление рисками» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 17001,
    "title": "Как открыть стартап",
    "authorId": "author-402",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 402,
    "subcategoryName": "Стартапы",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.8,
    "studentsCount": 18760,
    "lessonsCount": 12,
    "testsCount": 4,
    "tasksCount": 3,
    "shortDescription": "Стартовый курс по теме «Как открыть стартап» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 17002,
    "title": "Бизнес-модели",
    "authorId": "author-402",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 402,
    "subcategoryName": "Стартапы",
    "level": "intermediate",
    "durationLabel": "15 часов",
    "rating": 4.7,
    "studentsCount": 12340,
    "lessonsCount": 12,
    "testsCount": 2,
    "tasksCount": 4,
    "shortDescription": "Практический курс по теме «Бизнес-модели» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 17003,
    "title": "Поиск инвестиций",
    "authorId": "author-402",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 402,
    "subcategoryName": "Стартапы",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.6,
    "studentsCount": 8760,
    "lessonsCount": 16,
    "testsCount": 4,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «Поиск инвестиций» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 17004,
    "title": "MVP разработка",
    "authorId": "author-402",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 402,
    "subcategoryName": "Стартапы",
    "level": "intermediate",
    "durationLabel": "25 часов",
    "rating": 4.8,
    "studentsCount": 6540,
    "lessonsCount": 16,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Практический курс по теме «MVP разработка» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 17005,
    "title": "Масштабирование",
    "authorId": "author-402",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 402,
    "subcategoryName": "Стартапы",
    "level": "advanced",
    "durationLabel": "30 часов",
    "rating": 4.7,
    "studentsCount": 4320,
    "lessonsCount": 24,
    "testsCount": 6,
    "tasksCount": 9,
    "shortDescription": "Продвинутый курс по теме «Масштабирование» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 18001,
    "title": "Навыки лидера",
    "authorId": "author-403",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 403,
    "subcategoryName": "Лидерство",
    "level": "beginner",
    "durationLabel": "15 часов",
    "rating": 4.7,
    "studentsCount": 14320,
    "lessonsCount": 10,
    "testsCount": 3,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «Навыки лидера» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 18002,
    "title": "Управление командой",
    "authorId": "author-403",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 403,
    "subcategoryName": "Лидерство",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.8,
    "studentsCount": 9870,
    "lessonsCount": 15,
    "testsCount": 3,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «Управление командой» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 18003,
    "title": "Эмоциональный интеллект",
    "authorId": "author-403",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 403,
    "subcategoryName": "Лидерство",
    "level": "intermediate",
    "durationLabel": "15 часов",
    "rating": 4.9,
    "studentsCount": 7650,
    "lessonsCount": 13,
    "testsCount": 3,
    "tasksCount": 3,
    "shortDescription": "Практический курс по теме «Эмоциональный интеллект» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 18004,
    "title": "Мотивация сотрудников",
    "authorId": "author-403",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 403,
    "subcategoryName": "Лидерство",
    "level": "intermediate",
    "durationLabel": "15 часов",
    "rating": 4.7,
    "studentsCount": 5430,
    "lessonsCount": 10,
    "testsCount": 2,
    "tasksCount": 4,
    "shortDescription": "Практический курс по теме «Мотивация сотрудников» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 18005,
    "title": "Корпоративная культура",
    "authorId": "author-403",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 403,
    "subcategoryName": "Лидерство",
    "level": "advanced",
    "durationLabel": "20 часов",
    "rating": 4.6,
    "studentsCount": 3210,
    "lessonsCount": 16,
    "testsCount": 4,
    "tasksCount": 7,
    "shortDescription": "Продвинутый курс по теме «Корпоративная культура» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 19001,
    "title": "Финансовая грамотность",
    "authorId": "author-404",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 404,
    "subcategoryName": "Финансы",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.8,
    "studentsCount": 23450,
    "lessonsCount": 12,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Стартовый курс по теме «Финансовая грамотность» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 19002,
    "title": "Управление бюджетом",
    "authorId": "author-404",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 404,
    "subcategoryName": "Финансы",
    "level": "beginner",
    "durationLabel": "15 часов",
    "rating": 4.7,
    "studentsCount": 15430,
    "lessonsCount": 10,
    "testsCount": 2,
    "tasksCount": 3,
    "shortDescription": "Стартовый курс по теме «Управление бюджетом» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 19003,
    "title": "Инвестиции",
    "authorId": "author-404",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 404,
    "subcategoryName": "Финансы",
    "level": "intermediate",
    "durationLabel": "25 часов",
    "rating": 4.8,
    "studentsCount": 12340,
    "lessonsCount": 19,
    "testsCount": 5,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «Инвестиции» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 19004,
    "title": "Налоги для бизнеса",
    "authorId": "author-404",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 404,
    "subcategoryName": "Финансы",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.6,
    "studentsCount": 8760,
    "lessonsCount": 13,
    "testsCount": 3,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «Налоги для бизнеса» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 19005,
    "title": "Финансовый анализ",
    "authorId": "author-404",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 404,
    "subcategoryName": "Финансы",
    "level": "advanced",
    "durationLabel": "30 часов",
    "rating": 4.7,
    "studentsCount": 5430,
    "lessonsCount": 24,
    "testsCount": 6,
    "tasksCount": 8,
    "shortDescription": "Продвинутый курс по теме «Финансовый анализ» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 20001,
    "title": "Основы менеджмента",
    "authorId": "author-405",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 405,
    "subcategoryName": "Менеджмент",
    "level": "beginner",
    "durationLabel": "25 часов",
    "rating": 4.7,
    "studentsCount": 16540,
    "lessonsCount": 15,
    "testsCount": 4,
    "tasksCount": 4,
    "shortDescription": "Стартовый курс по теме «Основы менеджмента» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 20002,
    "title": "Стратегический менеджмент",
    "authorId": "author-405",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 405,
    "subcategoryName": "Менеджмент",
    "level": "intermediate",
    "durationLabel": "30 часов",
    "rating": 4.8,
    "studentsCount": 9870,
    "lessonsCount": 22,
    "testsCount": 4,
    "tasksCount": 7,
    "shortDescription": "Практический курс по теме «Стратегический менеджмент» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 20003,
    "title": "Операционный менеджмент",
    "authorId": "author-405",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 405,
    "subcategoryName": "Менеджмент",
    "level": "intermediate",
    "durationLabel": "25 часов",
    "rating": 4.6,
    "studentsCount": 7650,
    "lessonsCount": 19,
    "testsCount": 5,
    "tasksCount": 7,
    "shortDescription": "Практический курс по теме «Операционный менеджмент» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 20004,
    "title": "Управление качеством",
    "authorId": "author-405",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 405,
    "subcategoryName": "Менеджмент",
    "level": "advanced",
    "durationLabel": "20 часов",
    "rating": 4.7,
    "studentsCount": 5430,
    "lessonsCount": 15,
    "testsCount": 3,
    "tasksCount": 5,
    "shortDescription": "Продвинутый курс по теме «Управление качеством» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 20005,
    "title": "Кросс-культурный менеджмент",
    "authorId": "author-405",
    "categoryId": 4,
    "categoryName": "Бизнес и управление",
    "categoryIcon": "💼",
    "subcategoryId": 405,
    "subcategoryName": "Менеджмент",
    "level": "advanced",
    "durationLabel": "25 часов",
    "rating": 4.5,
    "studentsCount": 3210,
    "lessonsCount": 20,
    "testsCount": 5,
    "tasksCount": 7,
    "shortDescription": "Продвинутый курс по теме «Кросс-культурный менеджмент» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 21001,
    "title": "Английский для начинающих",
    "authorId": "author-501",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 501,
    "subcategoryName": "Английский язык",
    "level": "beginner",
    "durationLabel": "40 часов",
    "rating": 4.9,
    "studentsCount": 45670,
    "lessonsCount": 23,
    "testsCount": 6,
    "tasksCount": 8,
    "shortDescription": "Стартовый курс по теме «Английский для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 21002,
    "title": "Разговорный английский",
    "authorId": "author-501",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 501,
    "subcategoryName": "Английский язык",
    "level": "intermediate",
    "durationLabel": "35 часов",
    "rating": 4.8,
    "studentsCount": 32450,
    "lessonsCount": 25,
    "testsCount": 5,
    "tasksCount": 9,
    "shortDescription": "Практический курс по теме «Разговорный английский» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 21003,
    "title": "Бизнес английский",
    "authorId": "author-501",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 501,
    "subcategoryName": "Английский язык",
    "level": "intermediate",
    "durationLabel": "30 часов",
    "rating": 4.8,
    "studentsCount": 21340,
    "lessonsCount": 23,
    "testsCount": 5,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «Бизнес английский» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 21004,
    "title": "Английский для IT",
    "authorId": "author-501",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 501,
    "subcategoryName": "Английский язык",
    "level": "intermediate",
    "durationLabel": "25 часов",
    "rating": 4.9,
    "studentsCount": 18760,
    "lessonsCount": 16,
    "testsCount": 4,
    "tasksCount": 6,
    "shortDescription": "Практический курс по теме «Английский для IT» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 21005,
    "title": "Подготовка к IELTS",
    "authorId": "author-501",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 501,
    "subcategoryName": "Английский язык",
    "level": "advanced",
    "durationLabel": "45 часов",
    "rating": 4.7,
    "studentsCount": 15430,
    "lessonsCount": 35,
    "testsCount": 9,
    "tasksCount": 13,
    "shortDescription": "Продвинутый курс по теме «Подготовка к IELTS» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 22001,
    "title": "Немецкий с нуля",
    "authorId": "author-502",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 502,
    "subcategoryName": "Немецкий язык",
    "level": "beginner",
    "durationLabel": "40 часов",
    "rating": 4.7,
    "studentsCount": 14320,
    "lessonsCount": 23,
    "testsCount": 6,
    "tasksCount": 9,
    "shortDescription": "Стартовый курс по теме «Немецкий с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 22002,
    "title": "Разговорный немецкий",
    "authorId": "author-502",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 502,
    "subcategoryName": "Немецкий язык",
    "level": "intermediate",
    "durationLabel": "35 часов",
    "rating": 4.6,
    "studentsCount": 8760,
    "lessonsCount": 25,
    "testsCount": 5,
    "tasksCount": 7,
    "shortDescription": "Практический курс по теме «Разговорный немецкий» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 22003,
    "title": "Немецкий для работы",
    "authorId": "author-502",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 502,
    "subcategoryName": "Немецкий язык",
    "level": "intermediate",
    "durationLabel": "30 часов",
    "rating": 4.7,
    "studentsCount": 6540,
    "lessonsCount": 23,
    "testsCount": 5,
    "tasksCount": 7,
    "shortDescription": "Практический курс по теме «Немецкий для работы» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 22004,
    "title": "Экзамен Goethe",
    "authorId": "author-502",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 502,
    "subcategoryName": "Немецкий язык",
    "level": "advanced",
    "durationLabel": "40 часов",
    "rating": 4.6,
    "studentsCount": 4320,
    "lessonsCount": 30,
    "testsCount": 7,
    "tasksCount": 12,
    "shortDescription": "Продвинутый курс по теме «Экзамен Goethe» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 22005,
    "title": "Немецкий для путешествий",
    "authorId": "author-502",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 502,
    "subcategoryName": "Немецкий язык",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.8,
    "studentsCount": 9870,
    "lessonsCount": 12,
    "testsCount": 4,
    "tasksCount": 3,
    "shortDescription": "Стартовый курс по теме «Немецкий для путешествий» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 23001,
    "title": "Французский для начинающих",
    "authorId": "author-503",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 503,
    "subcategoryName": "Французский язык",
    "level": "beginner",
    "durationLabel": "40 часов",
    "rating": 4.7,
    "studentsCount": 12340,
    "lessonsCount": 23,
    "testsCount": 6,
    "tasksCount": 7,
    "shortDescription": "Стартовый курс по теме «Французский для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 23002,
    "title": "Разговорный французский",
    "authorId": "author-503",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 503,
    "subcategoryName": "Французский язык",
    "level": "intermediate",
    "durationLabel": "35 часов",
    "rating": 4.6,
    "studentsCount": 7650,
    "lessonsCount": 25,
    "testsCount": 5,
    "tasksCount": 8,
    "shortDescription": "Практический курс по теме «Разговорный французский» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 23003,
    "title": "Французский для бизнеса",
    "authorId": "author-503",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 503,
    "subcategoryName": "Французский язык",
    "level": "intermediate",
    "durationLabel": "30 часов",
    "rating": 4.5,
    "studentsCount": 5430,
    "lessonsCount": 23,
    "testsCount": 5,
    "tasksCount": 8,
    "shortDescription": "Практический курс по теме «Французский для бизнеса» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 23004,
    "title": "Подготовка к DELF",
    "authorId": "author-503",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 503,
    "subcategoryName": "Французский язык",
    "level": "advanced",
    "durationLabel": "45 часов",
    "rating": 4.7,
    "studentsCount": 3210,
    "lessonsCount": 34,
    "testsCount": 8,
    "tasksCount": 11,
    "shortDescription": "Продвинутый курс по теме «Подготовка к DELF» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 23005,
    "title": "Французская культура",
    "authorId": "author-503",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 503,
    "subcategoryName": "Французский язык",
    "level": "intermediate",
    "durationLabel": "20 часов",
    "rating": 4.8,
    "studentsCount": 4320,
    "lessonsCount": 14,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Практический курс по теме «Французская культура» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 24001,
    "title": "Испанский с нуля",
    "authorId": "author-504",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 504,
    "subcategoryName": "Испанский язык",
    "level": "beginner",
    "durationLabel": "40 часов",
    "rating": 4.8,
    "studentsCount": 15430,
    "lessonsCount": 23,
    "testsCount": 6,
    "tasksCount": 8,
    "shortDescription": "Стартовый курс по теме «Испанский с нуля» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 24002,
    "title": "Разговорный испанский",
    "authorId": "author-504",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 504,
    "subcategoryName": "Испанский язык",
    "level": "intermediate",
    "durationLabel": "35 часов",
    "rating": 4.7,
    "studentsCount": 9870,
    "lessonsCount": 25,
    "testsCount": 5,
    "tasksCount": 9,
    "shortDescription": "Практический курс по теме «Разговорный испанский» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 24003,
    "title": "Испанский для путешествий",
    "authorId": "author-504",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 504,
    "subcategoryName": "Испанский язык",
    "level": "beginner",
    "durationLabel": "20 часов",
    "rating": 4.9,
    "studentsCount": 12340,
    "lessonsCount": 14,
    "testsCount": 4,
    "tasksCount": 3,
    "shortDescription": "Стартовый курс по теме «Испанский для путешествий» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 24004,
    "title": "DELE подготовка",
    "authorId": "author-504",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 504,
    "subcategoryName": "Испанский язык",
    "level": "advanced",
    "durationLabel": "45 часов",
    "rating": 4.6,
    "studentsCount": 5430,
    "lessonsCount": 34,
    "testsCount": 8,
    "tasksCount": 12,
    "shortDescription": "Продвинутый курс по теме «DELE подготовка» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 24005,
    "title": "Латиноамериканский испанский",
    "authorId": "author-504",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 504,
    "subcategoryName": "Испанский язык",
    "level": "intermediate",
    "durationLabel": "30 часов",
    "rating": 4.7,
    "studentsCount": 4320,
    "lessonsCount": 21,
    "testsCount": 5,
    "tasksCount": 8,
    "shortDescription": "Практический курс по теме «Латиноамериканский испанский» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 25001,
    "title": "Китайский для начинающих",
    "authorId": "author-505",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 505,
    "subcategoryName": "Китайский язык",
    "level": "beginner",
    "durationLabel": "50 часов",
    "rating": 4.7,
    "studentsCount": 18760,
    "lessonsCount": 29,
    "testsCount": 7,
    "tasksCount": 10,
    "shortDescription": "Стартовый курс по теме «Китайский для начинающих» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 25002,
    "title": "Иероглифика",
    "authorId": "author-505",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 505,
    "subcategoryName": "Китайский язык",
    "level": "beginner",
    "durationLabel": "30 часов",
    "rating": 4.6,
    "studentsCount": 12340,
    "lessonsCount": 19,
    "testsCount": 4,
    "tasksCount": 5,
    "shortDescription": "Стартовый курс по теме «Иероглифика» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 25003,
    "title": "Разговорный китайский",
    "authorId": "author-505",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 505,
    "subcategoryName": "Китайский язык",
    "level": "intermediate",
    "durationLabel": "40 часов",
    "rating": 4.7,
    "studentsCount": 8760,
    "lessonsCount": 29,
    "testsCount": 7,
    "tasksCount": 9,
    "shortDescription": "Практический курс по теме «Разговорный китайский» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 25004,
    "title": "Бизнес китайский",
    "authorId": "author-505",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 505,
    "subcategoryName": "Китайский язык",
    "level": "intermediate",
    "durationLabel": "35 часов",
    "rating": 4.5,
    "studentsCount": 5430,
    "lessonsCount": 23,
    "testsCount": 5,
    "tasksCount": 9,
    "shortDescription": "Практический курс по теме «Бизнес китайский» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  },
  {
    "id": 25005,
    "title": "Подготовка к HSK",
    "authorId": "author-505",
    "categoryId": 5,
    "categoryName": "Иностранные языки",
    "categoryIcon": "🌍",
    "subcategoryId": 505,
    "subcategoryName": "Китайский язык",
    "level": "advanced",
    "durationLabel": "55 часов",
    "rating": 4.8,
    "studentsCount": 4320,
    "lessonsCount": 42,
    "testsCount": 10,
    "tasksCount": 14,
    "shortDescription": "Продвинутый курс по теме «Подготовка к HSK» с понятной структурой, регулярной практикой и проверкой прогресса на каждом этапе.",
    "coverUrl": ""
  }
];
