import logging
from collections.abc import Awaitable, Callable
from typing import TYPE_CHECKING, Any, Final

from faststream import BaseMiddleware
from faststream.message import StreamMessage

if TYPE_CHECKING:
    from dishka import AsyncContainer

from answer_service.application.commands.inbox.check_inbox import (
    CheckInboxCommand,
    CheckInboxCommandHandler,
)
from answer_service.application.errors import DuplicateInboxMessageError

logger: Final[logging.Logger] = logging.getLogger(__name__)


class InboxMiddleware(BaseMiddleware):  # type: ignore[type-arg, unused-ignore]
    """Deduplication middleware for RabbitMQ consumers.

    Delegates deduplication logic to CheckInboxCommandHandler. Catches
    DuplicateInboxMessageError to ack and discard already-processed messages.

    Runs inside the DishkaMiddleware scope: registered via insert_middleware
    before setup_dishka so that DishkaMiddleware ends up outermost.

    If the publisher did not set a message_id on the AMQP message the message
    is forwarded without deduplication — the correlation_id generated by
    FastStream is ephemeral and cannot serve as a stable idempotency key.
    """

    async def consume_scope(
        self,
        call_next: Callable[[Any], Awaitable[Any]],
        msg: StreamMessage[Any],
    ) -> Any:
        message_id: str | None = getattr(msg.raw_message, "message_id", None)

        if not message_id:
            logger.debug("Inbox: no message_id on raw message, skipping deduplication")
            return await call_next(msg)

        request_container: AsyncContainer = self.context.get_local("dishka")
        handler: CheckInboxCommandHandler = await request_container.get(
            CheckInboxCommandHandler
        )

        try:
            await handler(CheckInboxCommand(message_id=message_id))
        except DuplicateInboxMessageError:
            logger.info("Inbox: duplicate message_id=%s, skipping", message_id)
            await msg.ack()
            return None

        return await call_next(msg)
