export const mockSteps = [
  {
    id: "python-beginners-m1-l1-step-1",
    lessonId: "python-beginners-module-1-lesson-1",
    position: 1,
    type: "theory",
    title: "Что такое Python и как работает print",
    points: 0,
    contentRef: "python/module-1/lesson-1/step-1.md",
    graderId: null,
  },
  {
    id: "python-beginners-m1-l1-step-2",
    lessonId: "python-beginners-module-1-lesson-1",
    position: 2,
    type: "theory",
    title: "Переменные и строки",
    points: 0,
    contentRef: "python/module-1/lesson-1/step-2.md",
    graderId: null,
  },
  {
    id: "python-beginners-m1-l1-step-3",
    lessonId: "python-beginners-module-1-lesson-1",
    position: 3,
    type: "quiz_choice",
    title: "Что выведет программа",
    points: 1,
    contentRef: "python/module-1/lesson-1/step-3.md",
    graderId: "grader-python-beginners-m1-l1-step-3",
  },
  {
    id: "python-beginners-m1-l1-step-4",
    lessonId: "python-beginners-module-1-lesson-1",
    position: 4,
    type: "quiz_text",
    title: "Введите тип значения",
    points: 1,
    contentRef: "python/module-1/lesson-1/step-4.md",
    graderId: "grader-python-beginners-m1-l1-step-4",
  },
  {
    id: "python-beginners-m1-l1-step-5",
    lessonId: "python-beginners-module-1-lesson-1",
    position: 5,
    type: "code",
    title: "Приветствие пользователя",
    points: 2,
    contentRef: "python/module-1/lesson-1/step-5.md",
    graderId: "grader-python-beginners-m1-l1-step-5",
  },
  {
    id: "python-beginners-m1-l1-step-6",
    lessonId: "python-beginners-module-1-lesson-1",
    position: 6,
    type: "code",
    title: "Сумма двух чисел",
    points: 3,
    contentRef: "python/module-1/lesson-1/step-6.md",
    graderId: "grader-python-beginners-m1-l1-step-6",
  },
];
