export const mockLessons = [
  {
    id: "python-beginners-module-1-lesson-1",
    courseId: 1001,
    moduleId: "python-beginners-module-1",
    moduleTitle: "Основы Python",
    title: "Что такое Python и как работает print",
    position: 1,
    type: "theory",
    points: 0,
    contentRef: "python/module-1/lesson-1/step-1.md",
  },
  {
    id: "python-beginners-module-1-lesson-2",
    courseId: 1001,
    moduleId: "python-beginners-module-1",
    moduleTitle: "Основы Python",
    title: "Переменные и строки",
    position: 2,
    type: "theory",
    points: 0,
    contentRef: "python/module-1/lesson-1/step-2.md",
  },
  {
    id: "python-beginners-module-1-lesson-3",
    courseId: 1001,
    moduleId: "python-beginners-module-1",
    moduleTitle: "Основы Python",
    title: "Что выведет программа",
    position: 3,
    type: "quiz",
    points: 1,
    contentRef: "python/module-1/lesson-1/step-3.md",
    questions: [
      {
        id: "python-beginners-m1-l3-question-1",
        type: "single_choice",
        text: "Какой результат работы программы является корректным?",
        options: [
          { id: "a", label: "Hello", isCorrect: false },
          { id: "b", label: "Привет", isCorrect: true },
          { id: "c", label: "Ошибка", isCorrect: false },
        ],
      },
    ],
  },
  {
    id: "python-beginners-module-1-lesson-4",
    courseId: 1001,
    moduleId: "python-beginners-module-1",
    moduleTitle: "Основы Python",
    title: "Введите тип значения",
    position: 4,
    type: "quiz",
    points: 1,
    contentRef: "python/module-1/lesson-1/step-4.md",
    questions: [
      {
        id: "python-beginners-m1-l4-question-1",
        type: "text",
        text: "Как называется строковый тип данных в Python?",
        acceptedAnswers: ["str", "string"],
        trim: true,
        ignoreCase: true,
      },
    ],
  },
  {
    id: "python-beginners-module-1-lesson-5",
    courseId: 1001,
    moduleId: "python-beginners-module-1",
    moduleTitle: "Основы Python",
    title: "Приветствие пользователя",
    position: 5,
    type: "code",
    points: 2,
    contentRef: "python/module-1/lesson-1/step-5.md",
    grader: {
      language: "python",
      runner: "stdin_stdout",
      starterCode: 'name = input()\nprint("Привет, " + name + "!")',
      mockExecution: {
        strategy: "contains",
        requiredSnippets: ["input(", "print(", "Привет", "!"],
      },
      visibleCases: [
        {
          input: "Баграт\n",
          expectedOutput: "Привет, Баграт!\n",
        },
      ],
      hiddenCases: [
        {
          input: "Анна\n",
          expectedOutput: "Привет, Анна!\n",
        },
      ],
    },
  },
  {
    id: "python-beginners-module-1-lesson-6",
    courseId: 1001,
    moduleId: "python-beginners-module-1",
    moduleTitle: "Основы Python",
    title: "Сумма двух чисел",
    position: 6,
    type: "code",
    points: 3,
    contentRef: "python/module-1/lesson-1/step-6.md",
    grader: {
      language: "python",
      runner: "stdin_stdout",
      starterCode: "a = int(input())\nb = int(input())\nprint(a + b)",
      mockExecution: {
        strategy: "contains",
        requiredSnippets: ["input(", "int(", "print(", "+"],
      },
      visibleCases: [
        {
          input: "2\n3\n",
          expectedOutput: "5\n",
        },
      ],
      hiddenCases: [
        {
          input: "10\n7\n",
          expectedOutput: "17\n",
        },
        {
          input: "0\n0\n",
          expectedOutput: "0\n",
        },
      ],
    },
  },
];
