databaseChangeLog:
  - include:
      file: migrations/v.1.0.0/init.sql
  - include:
      file: migrations/v.1.0.1/seed-demo-users.sql
  - include:
      file: migrations/v.1.0.2/fix-demo-users-required-fields.sql
  - include:
      file: migrations/v.1.0.3/delete-spring-demo-user.sql
  - include:
      file: migrations/v.1.0.4/restore-spring-demo-user.sql
